version: '3.7'
services:
  front:
    container_name: front
    image: nginx
  back:
    container_name: back
    image: httpd
  postgres:
    container_name: postgres
    image: postgres:15.1
    env_file:
      - ../.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    links:
      - front
      - back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./templates:/etc/nginx/templates
    env_file:
      - ../.env