version: '3.7'
services:
  front:
    container_name: front
    image: nginx
  back:
    container_name: back
    image: httpd
  mysql:
    container_name: mysql
    image: mysql:8.0-debian
    volumes:
      - ./mysql:/var/lib/mysql
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    links:
      - front
      - back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./templates:/etc/nginx/templates