version: '3.7'
services:
  front:
    build:
      context: /home/adminuser/repo/front
    container_name: front
    env_file:
      - /home/adminuser/repo/front/.env

  back:
    build:
      context: /home/adminuser/repo/back
    container_name: back
    env_file:
      - /home/adminuser/repo/back/.env

  mysql:
    container_name: mysql
    image: mysql:8.0-debian
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iamthepassword
      - MYSQL_DATABASE=48hoursYnov
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=iamthepassword
    env_file:
      - ../ansible/src/.envback

  nginx:
    container_name: nginx
    image: nginx:1.23.3
    links:
      - front
      - back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./templates:/etc/nginx/templates